all-stop:
	@nosetests --verbose --stop --nocapture --nologcapture --pdb --detailed-errors UDStatic_test.py

all-cont:
	@nosetests --verbose --nocapture --nologcapture --pdb --detailed-errors UDStatic_test.py

failed:
	@nosetests --verbose --stop --nocapture --nologcapture --pdb --detailed-errors --failed UDStatic_test.py
