version: '3'

services:
  webapp:
    image: webapp
    build:
      context: .
    container_name: webapp
    ports:
      - 80-81:80-81
    restart: always
    working_dir: /var/www/uprzejmiedonosze.localhost/webapp
    volumes:
      - ../export:/var/www/uprzejmiedonosze.localhost/webapp
